<?
    // Librería de acciones y utilidades

    // Utilidades
    require("actions/ConfigFiles.act");
		require("../actions/GestionBD.act");
		require("../actions/Cookie.act");
		require("../actions/Mailer.act");
		require("../actions/Logger.act");	
		// Acciones
		require("actions/ShowForum.act");
		require("actions/ShowTemplates.act");
		require("actions/CreateTemplate.act");
		require("actions/DeleteTemplate.act");
		require("actions/Navigate.act");		
		require("actions/CreateUser.act");		
		require("actions/ShowUsers.act");
		require("actions/ShowUser.act");
		require("actions/EditUser.act");
		require("actions/ShowGroups.act");
		require("actions/ShowTheme.act");
		require("actions/EditForumInfo.act");
		require("actions/SendMail.act");
		require("actions/CreateCategorie.act");
		require("actions/EditCategorie.act");
		require("actions/DeleteCategorie.act");
		require("actions/CreateTheme.act");
		require("actions/EditTheme.act");
		require("actions/DeleteTheme.act");
		require("actions/DeleteUser.act");
		require("actions/CreateGroup.act");
		require("actions/EditGroup.act");
		require("actions/DeleteGroup.act");
		require("actions/ShowLogs.act");
		require("actions/ExportLogs.act");
		require("actions/ResetLogs.act");
?>
