<?
$body="
Ha recibidio un mensaje de \"".$forum_title."\":
___________________________________________________________________________

".$mensaje."
   
-->; Visite ".$forum_path.".
___________________________________________________________________________

Para dudas, quejas y/o sugerencias, escribir al administrador del foro [".$admin_email."]
___________________________________________________________________________
Beatriz Urbano Vega, 3º ASI, Proyecto Final - 2008 Copyright © / Diseño © D_sign
[http://www.abtu.net/inb/dsign/index.html]";
?>