<?
	$contador["empty"] = "templates/Default/img/contador_vacio.jpg";
	$contador[1] = "templates/Default/img/contador_10.jpg";
	$contador[2] = "templates/Default/img/contador_20.jpg";
	$contador[3] = "templates/Default/img/contador_30.jpg";
	$contador[4] = "templates/Default/img/contador_40.jpg";
	$contador[5] = "templates/Default/img/contador_50.jpg";
	$contador[6] = "templates/Default/img/contador_60.jpg";
	$contador[7] = "templates/Default/img/contador_70.jpg";
	$contador[8] = "templates/Default/img/contador_80.jpg";
	$contador[9] = "templates/Default/img/contador_90.jpg";	
	$contador["full"] = "templates/Default/img/contador_lleno.jpg";
?>
