<TD style="text-align: left; width: 380px;">
    <INPUT type="button" class="button" name="responder" value="Nuevo" onClick="createMP()" />&nbsp;
		<INPUT type="button" class="button" style="width: 115px;" name="borrar" value="Borrar seleccionados" onClick="document.formDeleteMPs.submit()" />
		<INPUT type="button" class="button" name="vaciar" value="Vaciar bandeja" onClick="emptyBox('<?=$box?>')" />					
</TD>