<TR>		
    <TD width="10px"></TD>
		<TD style="text-align: left; width: 380px;">		   	    
		    <INPUT type="button" class="button" name="responder" value="Responder" onClick="responseMP('<?=$id_mp?>', '<?=$box?>')" />&nbsp;
				<INPUT type="button" class="button" name="borrar" value="Borrar" onClick="deleteMP('<?=$id_mp?>', '<?=$box?>')" />													
		</TD>
		<TD width="10px"></TD>
<TR>		