<TD width='7px'></TD>
<TD class='celda_panel_usuario' style='width: 420px;'>																							
		<UL id='admin_menu'>	
				<LI><A HREF="javascript:showMenu('1')" title='Configuración del foro'>Configuraci&oacute;n</A></LI>
				<LI><A HREF="javascript:showMenu('2')" title='Configuración del foro'>Categor&iacute;as</A></LI>
				<LI><A HREF="javascript:showMenu('3')" title='Configuración del foro'>Temas</A></LI>
				<LI><A HREF="javascript:showMenu('4')" title='Configuración del foro'>Usuarios</A></LI>
				<LI><A HREF="javascript:showMenu('5')" title='Configuración del foro'>Grupos</A></LI>
				<LI><A HREF="index.php?accion=ShowLogs" title='Configuración del foro'>Seguimiento</A></LI>
		</UL>
</TD>