<?
    // Librería de acciones y utilidades
    
    // Utilidades
    require("actions/ConfigFiles.act");
		require("actions/GestionBD.act");
		require("actions/Mailer.act");				
		require("actions/Cookie.act");	
		require("actions/Logger.act");	
		// Acciones
		require("actions/ShowForum.act");
		require("actions/ShowConnectedUsers.act");
		require("actions/Navigate.act");
		require("actions/SessionLogin.act");
		require("actions/SessionAdminLogin.act");
		require("actions/SessionLogout.act");
		require("actions/CreateUser.act");
		require("actions/NewPass.act");
		require("actions/ShowAllAsRead.act");
		require("actions/ShowUsers.act");
		require("actions/ShowUser.act");
		require("actions/EditUser.act");
		require("actions/ShowGroups.act");
		require("actions/Finder.act");		
		require("actions/ShowTheme.act");
		require("actions/ShowPost.act");
		require("actions/ShowMPs.act");
		require("actions/ShowMP.act");
		require("actions/CreateMP.act");			
		require("actions/DeleteMP.act");
		require("actions/ShowMsg.act");
		require("actions/CreateMsg.act");
		require("actions/EditMsg.act");
		require("actions/DeleteMsg.act");
		require("actions/CreatePost.act");
		require("actions/EditPost.act");
		require("actions/DeletePost.act");
		require("actions/VoteUser.act");
		require("actions/AlertUser.act");
?>
