<?
$body="
Le damos la bienvenida a su nuevo foro \"".$forum_title."\".
___________________________________________________________________________

A continuación le mostramos sus datos.			 
- LOGIN : ".$login."
- CLAVE : ".$clave."
- E-MAIL : ".$email."
   
Para ver y/o modificar sus datos acceda a su perfil:
".$forum_path."
___________________________________________________________________________

Para dudas, quejas y/o sugerencias, escribir al administrador del foro [".$admin_email."]
___________________________________________________________________________
Beatriz Urbano Vega, 3º ASI, Proyecto Final - 2008 Copyright © / Diseño © D_sign
[http://www.abtu.net/inb/dsign/index.html]";
?>