<?
  // Librería de objetos  
	require("includes/obj/grupo.obj");
	require("includes/obj/mensaje.obj");
	require("includes/obj/mp.obj");
	require("includes/obj/post.obj");
	require("includes/obj/tema.obj");
	require("includes/obj/categoria.obj");
	require("includes/obj/usuario.obj");
	require("includes/obj/accion.obj");	
	require("includes/obj/log.obj");
	require("includes/obj/busqueda.obj");
?>
